services:
  backend:
    build: ./backend/
    env_file:
      - backend/.env
    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tmaster"]
      interval: 2s
      timeout: 5s
      retries: 10

  migrate:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.migrate

    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?sslmode=disable"
    command: ["sh", "-c", "goose -dir ./migrations postgres \"$DATABASE_URL\" up"]
    
  clickhouse:
    image: clickhouse/clickhouse-server:26.8
    
    environment:
      CLICKHOUSE_DB: logs
      CLICKHOUSE_USER: ${CH_USER}
      CLICKHOUSE_PASSWORD: ${CH_PASSWORD}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1

    ports:
      - ${CH_PORT}
      - ${CH_NATIVE_TCP}

    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./docker/clickhouse/config.d:/etc/clickhouse-server/config.d:ro
      - ./docker/clickhouse/users.d:/etc/clickhouse-server/users.d
      - ./docker/clickhouse/init:/docker-entrypoint-initdb.d:ro

    ulimits:
      nofile:
        soft: 262144
        hard: 262144

    mem_limit: 1g
    cpus: 1.0

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1"
        ]
      interval: 5s
      timeout: 3s
      retries: 20

  vector:
    image: timberio/vector:0.51.1-alpine

    depends_on:
      clickhouse:
        condition: service_healthy

    volumes:
      - ./docker/vector/vector.yaml:/etc/vector/vector.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - vector_data:/var/lib/vector

    command:
      - "--config"
      - "/etc/vector/vector.yaml"

    mem_limit: 256m
    cpus: 0.5
    
volumes:
  postgres_data:
  clickhouse_data:
  vector_data: